language: node_js

node_js:
  - 0.10
  
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
before_script:
  - npm cache clean
  - npm install -g bower grunt-cli
  - bower install

script: grunt

notifications:
  email:
    recipients:
      - fabio.scala@gmail.com
    on_success: change
    on_failure: always